### ISSUE TITLE
eigen_conversions does not have a method for msg to Eigen matrix

### ISSUE THREAD

**Issue by anuppari** [ros/geometry#139]
There is a function for converting a generic Eigen matrix to a `std_msgs` multidimensional array [here](https://github.com/ros/geometry/blob/4861b35f4c556def1f924d6d7e079b3c327b5586/eigen_conversions/include/eigen_conversions/eigen_msg.h#L107), but no corresponding function to go back the other way.

**Comment by tfoote** [comment]
I could consider merging a PR to add that. However both this package is deprecated for http://wiki.ros.org/tf2_eigen and the std_msgs MultiDimentionalArrays datatypes are generally not recommended either.

**Comment by anuppari** [comment]
If that message type is not recommended, and since tf2 focuses on geometric types, what's the best way to send generic Eigen matrices over ROS topics?

**Comment by tfoote** [comment]
We generally discourage sending generic matrices as messages since they are not semantically meaningful. The MultiDimentialArrays are likely the best way to do that, but you need to keep in mind that the messages might be logged or otherwise used and are best being fully self contained and documented.
