### ISSUE TITLE
the python listner cannot get the exist transform

### ISSUE THREAD

**Issue by xs-alt** [ros/geometry#162]
Hi all, today l find one strange thing when l use tf(python) to get the transform published by my cpp  node. 
![2018-04-20 21-33-10](https://user-images.githubusercontent.com/24916161/39053805-7c8af402-44e2-11e8-9eb7-f221f07cb0c5.png)
then l use python tf 
![2018-04-20 21-33-58](https://user-images.githubusercontent.com/24916161/39053848-a2a4e6b6-44e2-11e8-91c9-3513a619a5e3.png)
well, some error happens
![2018-04-20 21-34-59](https://user-images.githubusercontent.com/24916161/39053880-bd315488-44e2-11e8-8595-55f43c0385be.png)
However, if l use the cpp node listener , it works.
![2018-04-20 21-37-47](https://user-images.githubusercontent.com/24916161/39054001-15fccfe8-44e3-11e8-9819-cbe12bdc9898.png)

;( seems strange and no idea what's wrong 
l am under Ubuntu 16.04, ROS Kinetic

**Comment by xs-alt** [comment]
![2018-04-20 21-42-38](https://user-images.githubusercontent.com/24916161/39054285-c943cfe8-44e3-11e8-9d52-6b92c59fa6c7.png)
l run rqt_tf_tree to look what happens, and picture tells.

**Comment by tfoote** [comment]
Please ask questions on http://answers.ros.org according to our support policy: http://wiki.ros.org/Support We try to keep the issue tracker reserved for bugs and feature developments.

Also mentioned there, please don't use screenshots of text. They can't be searched or reproduced easily. Copy and paste them instead and use code blocks.

Your problem is that you're not giving the buffer any time to populate before querying it. You'll find there are already many similar questions on answers.ros.org with this same problem. Please search there for other releated questions. And see part 3 of this about try blocks: http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28C%2B%2B%29 or here: http://wiki.ros.org/tf/Tutorials/Writing%20a%20tf%20listener%20%28Python%29
