### ISSUE TITLE
eigen > eigen2 > eigen3 ?????

### ISSUE THREAD

**Issue by kennydedavion** [ros/geometry#232]
hello, can you please explain to me why if I install a geometry package that contains eigen, I then have to install eigen2 and then it requires the eigen3 package? This is not normal people !!! Isn't anyone able to really create something similar to rosdep, which will be able to install dependencies? whether they are catkin or necatkin and bezcatkin? I feel like you haven't cooperated with the creators at all. the process of adding new versions, does not support the package and completely banal problems, which, however, man did not know. you just can't make one package that works for everything, based on the platform where I'm pushing it?
it's been more than a year since I first discovered ROS and its balicas. I found one project that I am copying. but the tutorial is on an older version and its creator is already elsewhere, so it does not maintain or respond to it. and the answers of most creators are hot potatoes. the problem is not in my package, contact linux support elsewhere, and blah blah blah. but since then every time I added a device or a sensor, a picamer and had to download balers, there was always, ALWAYS, there was a problem with the necessary baler. finally look at some neurotic, skeptic, kinetic and idiotic melodic and finally make one working system that will not have flies and will be written so that I do not have to find out why when I downloaded the geometry of the kinetic package, which according to ros-wiki is used as indigo. does the package require eigen conversation and does it refer to eigen3? seriously? everywhere everyone writes how there is no need to reinvent the wheel. but try to make a 25 "electron on dodge ram at home. aha?

**Comment by tfoote** [comment]
> can you please explain to me why if I install a geometry package that contains eigen, I then have to install eigen2 and then it requires the eigen3 package? 

This doesn't sound like it makes sense. In general we use the system maintained version of eigen via rosdep. The rosdep key is viewable here on most platforms: https://index.ros.org/d/eigen/

There are two packages in this repository that use the `eigen` key: [tf_conversions](https://github.com/ros/geometry/blob/63c3c7b404b8f390061bdadc5bc675e7ae5808be/tf_conversions/package.xml#L24) 
 and 
[eigen_conversions](https://github.com/ros/geometry/blob/63c3c7b404b8f390061bdadc5bc675e7ae5808be/eigen_conversions/package.xml#L21)

It's not clear where you're getting references to eigen2 from. 

It sounds like you're following relatively old installation instructions from different sources and using long EOL branches. (Indigo and Kinetic are long since EOL'd) But we did use older versions of eigen in the past. if you're trying to use those branches they may need older versions of Eigen which was current at that time. 

I'm going to close this as it appears to be more of a rant than a actionable ticket.
