### ISSUE TITLE
kdl/eigen/msgs conversions with static method overloading

### ISSUE THREAD

**Issue by goretkin** [ros/geometry#95]
Instead of having separate names for conversion methods `pointKDLToMsg` and `poseKDLToMsg`, the functions could have the same name and be overloaded based on the type of arguments. I think This is a good case for method overloading.

**Comment by tfoote** [comment]
Yes it can be done. While using overloaded methods provide shorter method names it makes debugging/introspection harder due to ambiguity of which implementation will be selected. 

tf2 has an more fully featured datatype conversion methods. See the [tutorial](http://wiki.ros.org/tf2/Tutorials/Migration/DataConversions).

As this is a stylistic choice and this is a stable released API I don't plan to change the API.
